# Generated by Django 4.0.6 on 2022-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_phone_slug_alter_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
